name: Python CI Pipeline

on:
  push:
    branches:
      - master
      - ResolveBugs
  pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run tests
    - name: Run Python tests
      run: python Test.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
